# Generated by Django 4.2.7 on 2025-09-10 20:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DormitoryBuilding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='نام ساختمان')),
                ('code', models.CharField(max_length=20, verbose_name='کد ساختمان')),
                ('floor_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='تعداد طبقات')),
                ('construction_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(1500)], verbose_name='سال ساخت')),
                ('total_area', models.PositiveIntegerField(blank=True, null=True, verbose_name='مساحت کل (متر مربع)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('maintenance_status', models.CharField(choices=[('GOOD', 'خوب'), ('FAIR', 'متوسط'), ('POOR', 'نیاز به تعمیر'), ('UNDER_MAINTENANCE', 'در حال تعمیر')], default='GOOD', max_length=20, verbose_name='وضعیت نگهداری')),
                ('has_elevator', models.BooleanField(default=False, verbose_name='آسانسور')),
                ('has_laundry', models.BooleanField(default=False, verbose_name='رختشویخانه')),
                ('has_kitchen', models.BooleanField(default=False, verbose_name='آشپزخانه')),
                ('has_study_room', models.BooleanField(default=False, verbose_name='اتاق مطالعه')),
                ('has_prayer_room', models.BooleanField(default=False, verbose_name='نمازخانه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'ساختمان خوابگاه',
                'verbose_name_plural': 'ساختمان\u200cهای خوابگاه',
                'ordering': ['complex', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DormitoryComplex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='نام مجموعه خوابگاهی')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='نام انگلیسی')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد مجموعه')),
                ('gender', models.CharField(choices=[('MALE', 'برادران'), ('FEMALE', 'خواهران')], max_length=10, verbose_name='جنسیت')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تأسیس')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('facilities', models.JSONField(blank=True, default=list, verbose_name='امکانات')),
                ('rules', models.JSONField(blank=True, default=list, verbose_name='قوانین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_dormitory_complexes', to=settings.AUTH_USER_MODEL, verbose_name='مدیر مجموعه خوابگاهی')),
            ],
            options={
                'verbose_name': 'مجموعه خوابگاهی',
                'verbose_name_plural': 'مجموعه\u200cهای خوابگاهی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DormitoryFloor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('floor_number', models.PositiveIntegerField(verbose_name='شماره طبقه')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='نام طبقه')),
                ('has_common_room', models.BooleanField(default=False, verbose_name='اتاق مشترک')),
                ('has_kitchen', models.BooleanField(default=False, verbose_name='آشپزخانه')),
                ('has_bathroom', models.BooleanField(default=True, verbose_name='سرویس بهداشتی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='dormitory.dormitorybuilding', verbose_name='ساختمان')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_floors', to=settings.AUTH_USER_MODEL, verbose_name='سرپرست طبقه')),
            ],
            options={
                'verbose_name': 'طبقه خوابگاه',
                'verbose_name_plural': 'طبقات خوابگاه',
                'ordering': ['building', 'floor_number'],
            },
        ),
        migrations.CreateModel(
            name='DormitoryRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=10, verbose_name='شماره اتاق')),
                ('room_code', models.CharField(max_length=50, unique=True, verbose_name='کد اتاق')),
                ('room_type', models.CharField(choices=[('SINGLE', 'یک نفره'), ('DOUBLE', 'دو نفره'), ('TRIPLE', 'سه نفره'), ('QUAD', 'چهار نفره'), ('SUITE', 'سوئیت')], max_length=10, verbose_name='نوع اتاق')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='ظرفیت')),
                ('area', models.PositiveIntegerField(blank=True, null=True, verbose_name='مساحت (متر مربع)')),
                ('status', models.CharField(choices=[('AVAILABLE', 'در دسترس'), ('OCCUPIED', 'اشغال شده'), ('MAINTENANCE', 'در تعمیر'), ('RESERVED', 'رزرو شده'), ('OUT_OF_ORDER', 'خارج از سرویس')], default='AVAILABLE', max_length=15, verbose_name='وضعیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('has_private_bathroom', models.BooleanField(default=False, verbose_name='سرویس اختصاصی')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='بالکن')),
                ('has_air_conditioning', models.BooleanField(default=False, verbose_name='کولر')),
                ('has_heating', models.BooleanField(default=True, verbose_name='گرمایش')),
                ('has_internet', models.BooleanField(default=True, verbose_name='اینترنت')),
                ('academic_level_restriction', models.JSONField(blank=True, default=list, help_text='مقاطع تحصیلی مجاز (لیست)', verbose_name='محدودیت مقطع تحصیلی')),
                ('min_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='حداقل معدل مورد نیاز')),
                ('special_conditions', models.JSONField(blank=True, default=list, help_text='شرایط خاص برای اسکان', verbose_name='شرایط خاص')),
                ('monthly_rent', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='اجاره ماهانه (تومان)')),
                ('deposit', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='ودیعه (تومان)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('maintenance_notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای نگهداری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='dormitory.dormitoryfloor', verbose_name='طبقه')),
            ],
            options={
                'verbose_name': 'اتاق خوابگاه',
                'verbose_name_plural': 'اتاق\u200cهای خوابگاه',
                'ordering': ['floor', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='DormitoryMaintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='شرح مشکل')),
                ('priority', models.CharField(choices=[('LOW', 'کم'), ('MEDIUM', 'متوسط'), ('HIGH', 'زیاد'), ('URGENT', 'فوری')], max_length=10, verbose_name='اولویت')),
                ('category', models.CharField(choices=[('ELECTRICAL', 'برق'), ('PLUMBING', 'لوله\u200cکشی'), ('HEATING', 'گرمایش'), ('COOLING', 'سرمایش'), ('FURNITURE', 'مبلمان'), ('CLEANING', 'نظافت'), ('SECURITY', 'امنیت'), ('OTHER', 'سایر')], max_length=50, verbose_name='دسته\u200cبندی')),
                ('status', models.CharField(choices=[('REPORTED', 'گزارش شده'), ('ASSIGNED', 'محول شده'), ('IN_PROGRESS', 'در حال انجام'), ('COMPLETED', 'تکمیل شده'), ('CANCELLED', 'لغو شده')], default='REPORTED', max_length=15, verbose_name='وضعیت')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ گزارش')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ محولی')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='هزینه تخمینی')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='هزینه واقعی')),
                ('admin_notes', models.TextField(blank=True, verbose_name='یادداشت مدیریت')),
                ('technician_notes', models.TextField(blank=True, verbose_name='یادداشت تکنسین')),
                ('completion_notes', models.TextField(blank=True, verbose_name='یادداشت تکمیل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenances', to=settings.AUTH_USER_MODEL, verbose_name='محول شده به')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_maintenances', to=settings.AUTH_USER_MODEL, verbose_name='گزارش\u200cدهنده')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='dormitory.dormitoryroom', verbose_name='اتاق')),
            ],
            options={
                'verbose_name': 'درخواست تعمیرات',
                'verbose_name_plural': 'درخواست\u200cهای تعمیرات',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.AddField(
            model_name='dormitorybuilding',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='dormitory.dormitorycomplex', verbose_name='مجموعه خوابگاهی'),
        ),
        migrations.AddField(
            model_name='dormitorybuilding',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_buildings', to=settings.AUTH_USER_MODEL, verbose_name='سرپرست ساختمان'),
        ),
        migrations.CreateModel(
            name='DormitoryAccommodation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ واقعی خروج')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار تأیید'), ('APPROVED', 'تأیید شده'), ('ACTIVE', 'فعال'), ('SUSPENDED', 'تعلیق'), ('TERMINATED', 'خاتمه یافته'), ('CANCELLED', 'لغو شده')], default='PENDING', max_length=15, verbose_name='وضعیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('monthly_payment', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='پرداخت ماهانه')),
                ('deposit_paid', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='ودیعه پرداخت شده')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید')),
                ('application_notes', models.TextField(blank=True, verbose_name='یادداشت درخواست')),
                ('admin_notes', models.TextField(blank=True, verbose_name='یادداشت مدیریت')),
                ('termination_reason', models.TextField(blank=True, verbose_name='دلیل خاتمه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_accommodations', to=settings.AUTH_USER_MODEL, verbose_name='تأیید کننده')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='dormitory.dormitoryroom', verbose_name='اتاق')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dormitory_accommodations', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'اسکان خوابگاه',
                'verbose_name_plural': 'اسکان\u200cهای خوابگاه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DormitoryStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('MANAGER', 'مدیر خوابگاه'), ('SUPERVISOR', 'سرپرست'), ('GUARD', 'نگهبان'), ('CLEANER', 'نظافتچی'), ('MAINTENANCE', 'تعمیرکار'), ('KITCHEN_STAFF', 'کارمند آشپزخانه'), ('ADMIN', 'اداری')], max_length=15, verbose_name='نقش')),
                ('shift', models.CharField(choices=[('MORNING', 'صبح'), ('EVENING', 'عصر'), ('NIGHT', 'شب'), ('FULL_TIME', 'تمام وقت')], max_length=10, verbose_name='شیفت')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('emergency_contact', models.JSONField(blank=True, default=dict, verbose_name='تماس اضطراری')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff', to='dormitory.dormitorybuilding', verbose_name='ساختمان محول شده')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='dormitory.dormitorycomplex', verbose_name='مجموعه خوابگاهی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dormitory_staff_roles', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کارمند خوابگاه',
                'verbose_name_plural': 'کارکنان خوابگاه',
                'ordering': ['complex', 'role', 'user__last_name'],
                'indexes': [models.Index(fields=['complex', 'role'], name='dormitory_d_complex_1e0024_idx'), models.Index(fields=['is_active'], name='dormitory_d_is_acti_20894f_idx')],
                'unique_together': {('user', 'complex', 'role')},
            },
        ),
        migrations.AddIndex(
            model_name='dormitoryroom',
            index=models.Index(fields=['room_code'], name='dormitory_d_room_co_8a51cc_idx'),
        ),
        migrations.AddIndex(
            model_name='dormitoryroom',
            index=models.Index(fields=['status'], name='dormitory_d_status_046fbd_idx'),
        ),
        migrations.AddIndex(
            model_name='dormitoryroom',
            index=models.Index(fields=['room_type'], name='dormitory_d_room_ty_373972_idx'),
        ),
        migrations.AddIndex(
            model_name='dormitoryroom',
            index=models.Index(fields=['floor', 'is_active'], name='dormitory_d_floor_i_37dee8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dormitoryroom',
            unique_together={('floor', 'room_number')},
        ),
        migrations.AddIndex(
            model_name='dormitorymaintenance',
            index=models.Index(fields=['status', 'priority'], name='dormitory_d_status_be0df5_idx'),
        ),
        migrations.AddIndex(
            model_name='dormitorymaintenance',
            index=models.Index(fields=['room'], name='dormitory_d_room_id_d7246a_idx'),
        ),
        migrations.AddIndex(
            model_name='dormitorymaintenance',
            index=models.Index(fields=['assigned_to'], name='dormitory_d_assigne_ff8407_idx'),
        ),
        migrations.AddIndex(
            model_name='dormitorymaintenance',
            index=models.Index(fields=['reported_at'], name='dormitory_d_reporte_dcd17f_idx'),
        ),
        migrations.AddIndex(
            model_name='dormitoryfloor',
            index=models.Index(fields=['building', 'floor_number'], name='dormitory_d_buildin_9d9d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='dormitoryfloor',
            index=models.Index(fields=['is_active'], name='dormitory_d_is_acti_bd418a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dormitoryfloor',
            unique_together={('building', 'floor_number')},
        ),
        migrations.AddIndex(
            model_name='dormitorycomplex',
            index=models.Index(fields=['gender'], name='dormitory_d_gender_54d579_idx'),
        ),
        migrations.AddIndex(
            model_name='dormitorycomplex',
            index=models.Index(fields=['is_active'], name='dormitory_d_is_acti_ca5a31_idx'),
        ),
        migrations.AddIndex(
            model_name='dormitorybuilding',
            index=models.Index(fields=['complex', 'is_active'], name='dormitory_d_complex_37f26b_idx'),
        ),
        migrations.AddIndex(
            model_name='dormitorybuilding',
            index=models.Index(fields=['maintenance_status'], name='dormitory_d_mainten_d265fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dormitorybuilding',
            unique_together={('complex', 'code')},
        ),
        migrations.AddIndex(
            model_name='dormitoryaccommodation',
            index=models.Index(fields=['student', 'status'], name='dormitory_d_student_ea08a5_idx'),
        ),
        migrations.AddIndex(
            model_name='dormitoryaccommodation',
            index=models.Index(fields=['room', 'is_active'], name='dormitory_d_room_id_9e899d_idx'),
        ),
        migrations.AddIndex(
            model_name='dormitoryaccommodation',
            index=models.Index(fields=['start_date', 'end_date'], name='dormitory_d_start_d_8eca63_idx'),
        ),
        migrations.AddIndex(
            model_name='dormitoryaccommodation',
            index=models.Index(fields=['status'], name='dormitory_d_status_cca516_idx'),
        ),
    ]
