# Generated by Django 5.2.5 on 2025-09-09 23:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام مجوز')),
                ('codename', models.CharField(max_length=50, unique=True, verbose_name='کد مجوز')),
                ('permission_type', models.CharField(choices=[('read', 'مشاهده'), ('write', 'ویرایش'), ('delete', 'حذف'), ('approve', 'تأیید'), ('manage', 'مدیریت'), ('report', 'گزارش\u200cگیری'), ('audit', 'بازرسی'), ('financial', 'مالی'), ('academic', 'آکادمیک'), ('administrative', 'اداری')], max_length=20, verbose_name='نوع مجوز')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('module', models.CharField(blank=True, max_length=50, verbose_name='ماژول')),
            ],
            options={
                'verbose_name': 'مجوز',
                'verbose_name_plural': 'مجوزها',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AddField(
            model_name='user',
            name='academic_rank',
            field=models.CharField(blank=True, choices=[('instructor', 'مربی'), ('assistant_professor', 'استادیار'), ('associate_professor', 'دانشیار'), ('professor', 'استاد'), ('emeritus_professor', 'استاد بازنشسته')], max_length=30, verbose_name='مرتبه علمی'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.CharField(blank=True, max_length=50, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='شماره پرسنلی'),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('permanent', 'رسمی'), ('contract', 'قراردادی'), ('project', 'پروژه\u200cای'), ('hourly', 'ساعتی'), ('visiting', 'مهمان'), ('retired', 'بازنشسته')], max_length=20, verbose_name='نوع استخدام'),
        ),
        migrations.AddField(
            model_name='user',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='نام پدر'),
        ),
        migrations.AddField(
            model_name='user',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100, verbose_name='رشته تحصیلی'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='user',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ استخدام'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تأیید شده'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, verbose_name='موبایل'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'کد ملی باید 10 رقم باشد')], verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='user',
            name='persian_first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='نام فارسی'),
        ),
        migrations.AddField(
            model_name='user',
            name='persian_last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='نام خانوادگی فارسی'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='تلفن'),
        ),
        migrations.AddField(
            model_name='user',
            name='salary_grade',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='پایه حقوقی'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'دانشجو'), ('faculty', 'عضو هیأت علمی'), ('staff', 'کارمند'), ('manager', 'مدیر'), ('president', 'رئیس دانشگاه'), ('vice_president', 'معاون'), ('dean', 'دکان دانشکده'), ('head_of_department', 'رئیس گروه'), ('researcher', 'پژوهشگر'), ('administrative', 'اداری'), ('financial', 'مالی'), ('technical', 'فنی'), ('security', 'امنیتی'), ('service', 'خدماتی'), ('undergraduate', 'کارشناسی'), ('graduate', 'کارشناسی ارشد'), ('phd', 'دکتری'), ('postdoc', 'فوق دکتری'), ('super_admin', 'مدیر کل سیستم'), ('system_admin', 'مدیر سیستم'), ('auditor', 'بازرس'), ('guest', 'مهمان')], default='student', max_length=30, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='شماره دانشجویی'),
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='عمل انجام شده')),
                ('resource', models.CharField(max_length=100, verbose_name='منبع')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('success', models.BooleanField(default=True, verbose_name='موفق')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ دسترسی',
                'verbose_name_plural': 'لاگ\u200cهای دسترسی',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام واحد')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد واحد')),
                ('unit_type', models.CharField(choices=[('university', 'دانشگاه'), ('presidency', 'حوزه ریاست'), ('vice_presidency', 'معاونت'), ('vice_education', 'معاونت آموزشی'), ('vice_research', 'معاونت پژوهش و فناوری'), ('vice_student', 'معاونت دانشجویی'), ('vice_planning', 'معاونت برنامه\u200cریزی و توسعه منابع'), ('vice_admin', 'معاونت اداری و مالی'), ('vice_construction', 'معاونت عمرانی'), ('vice_cultural', 'معاونت فرهنگی و اجتماعی'), ('vice_international', 'معاونت بین\u200cالملل'), ('vice_technology', 'معاونت فناوری\u200cهای دیجیتال'), ('faculty', 'دانشکده'), ('department', 'گروه آموزشی'), ('research_center', 'مرکز تحقیقاتی'), ('directorate_general', 'اداره کل'), ('directorate', 'اداره'), ('office', 'دفتر'), ('section', 'بخش'), ('unit', 'واحد'), ('organization', 'سازمان'), ('student_org', 'سازمان امور دانشجویی'), ('development_org', 'سازمان توسعه و سرمایه\u200cگذاری'), ('council', 'شورا'), ('board', 'هیأت'), ('committee', 'کمیته')], max_length=30, verbose_name='نوع واحد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.organizationalunit', verbose_name='واحد والد')),
            ],
            options={
                'verbose_name': 'واحد سازمانی',
                'verbose_name_plural': 'واحدهای سازمانی',
                'ordering': ['parent', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='primary_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_members', to='users.organizationalunit', verbose_name='واحد سازمانی اصلی'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان سمت')),
                ('position_level', models.CharField(choices=[('executive', 'مدیریت اجرایی'), ('senior', 'ارشد'), ('middle', 'میانی'), ('junior', 'مبتدی'), ('specialist', 'کارشناس'), ('expert', 'متخصص'), ('administrative', 'اداری'), ('service', 'خدماتی'), ('academic', 'هیأت علمی'), ('research', 'پژوهشی')], max_length=20, verbose_name='سطح سمت')),
                ('authority_level', models.IntegerField(choices=[(1, 'بدون اختیار خاص'), (2, 'اختیار محدود'), (3, 'اختیار متوسط'), (4, 'اختیار بالا'), (5, 'اختیار کامل')], default=1, verbose_name='سطح اختیار')),
                ('job_description', models.TextField(blank=True, verbose_name='شرح وظایف')),
                ('required_qualifications', models.TextField(blank=True, verbose_name='شرایط احراز')),
                ('salary_grade', models.PositiveIntegerField(blank=True, null=True, verbose_name='پایه حقوقی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizational_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='users.organizationalunit', verbose_name='واحد سازمانی')),
            ],
            options={
                'verbose_name': 'سمت سازمانی',
                'verbose_name_plural': 'سمت\u200cهای سازمانی',
                'unique_together': {('title', 'organizational_unit')},
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اعطا')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='اعطا شده توسط')),
                ('organizational_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organizationalunit', verbose_name='محدود به واحد')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.permission', verbose_name='مجوز')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions_custom', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مجوز کاربر',
                'verbose_name_plural': 'مجوزهای کاربران',
                'unique_together': {('user', 'permission', 'organizational_unit')},
            },
        ),
        migrations.CreateModel(
            name='UserPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_primary', models.BooleanField(default=False, verbose_name='سمت اصلی')),
                ('appointment_letter', models.CharField(blank=True, max_length=100, verbose_name='شماره حکم')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.position', verbose_name='سمت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تخصیص سمت',
                'verbose_name_plural': 'تخصیص\u200cهای سمت',
                'unique_together': {('user', 'position', 'start_date')},
            },
        ),
    ]
