# Generated by Django 4.2.7 on 2025-09-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_academicprogram_accesslevel_administrativeunit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('EMPLOYEE', 'کارمند'), ('STUDENT', 'دانشجو'), ('ADMIN', 'مدیر سیستم'), ('GUEST', 'مهمان')], default='EMPLOYEE', max_length=20, verbose_name='نوع کاربر'),
        ),
    ]
