# Generated by Django 4.2.7 on 2025-09-10 17:50

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=200)),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web Browser'), ('desktop', 'Desktop App')], max_length=20)),
                ('device_model', models.CharField(blank=True, max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=50)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('push_token', models.TextField(blank=True)),
                ('push_provider', models.CharField(blank=True, choices=[('fcm', 'Firebase Cloud Messaging'), ('apn', 'Apple Push Notification'), ('web', 'Web Push')], max_length=20)),
                ('push_enabled', models.BooleanField(default=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('last_location', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('login_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mobile Device',
                'verbose_name_plural': 'Mobile Devices',
                'db_table': 'mobile_devices',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='MobileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto (System)')], default='auto', max_length=10)),
                ('language', models.CharField(default='fa', max_length=10)),
                ('font_size', models.CharField(default='medium', max_length=10)),
                ('push_notifications', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('notification_sound', models.BooleanField(default=True)),
                ('notification_vibration', models.BooleanField(default=True)),
                ('auto_sync', models.BooleanField(default=True)),
                ('sync_on_wifi_only', models.BooleanField(default=False)),
                ('offline_storage_limit_mb', models.IntegerField(default=100)),
                ('location_tracking', models.BooleanField(default=False)),
                ('analytics_enabled', models.BooleanField(default=True)),
                ('crash_reporting', models.BooleanField(default=True)),
                ('image_quality', models.CharField(default='medium', max_length=10)),
                ('animation_enabled', models.BooleanField(default=True)),
                ('data_saver_mode', models.BooleanField(default=False)),
                ('custom_settings', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mobile Settings',
                'verbose_name_plural': 'Mobile Settings',
                'db_table': 'mobile_settings',
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(blank=True)),
                ('notification_type', models.CharField(choices=[('general', 'General'), ('announcement', 'Announcement'), ('grade', 'Grade Update'), ('assignment', 'Assignment'), ('exam', 'Exam'), ('schedule', 'Schedule Change'), ('message', 'Message'), ('reminder', 'Reminder')], max_length=20)),
                ('target_user_types', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.URLField(blank=True)),
                ('action_data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('total_recipients', models.IntegerField(default=0)),
                ('successful_sends', models.IntegerField(default=0)),
                ('failed_sends', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
                ('target_devices', models.ManyToManyField(blank=True, to='mobile_api.mobiledevice')),
                ('target_users', models.ManyToManyField(blank=True, related_name='push_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Notification',
                'verbose_name_plural': 'Push Notifications',
                'db_table': 'push_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='push_notifi_status_272981_idx'), models.Index(fields=['notification_type', 'created_at'], name='push_notifi_notific_6af839_idx'), models.Index(fields=['created_by'], name='push_notifi_created_21cc6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='OfflineSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('incremental', 'Incremental'), ('delta', 'Delta Sync')], max_length=20)),
                ('data_types', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('last_sync_token', models.CharField(blank=True, max_length=255)),
                ('current_sync_token', models.CharField(blank=True, max_length=255)),
                ('total_items', models.IntegerField(default=0)),
                ('synced_items', models.IntegerField(default=0)),
                ('failed_items', models.IntegerField(default=0)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('data_size_bytes', models.BigIntegerField(default=0)),
                ('compressed_size_bytes', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_records', to='mobile_api.mobiledevice')),
            ],
            options={
                'verbose_name': 'Offline Sync',
                'verbose_name_plural': 'Offline Syncs',
                'db_table': 'offline_sync',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'status'], name='offline_syn_device__f62b4a_idx'), models.Index(fields=['sync_type', 'created_at'], name='offline_syn_sync_ty_b1c5f3_idx'), models.Index(fields=['status', 'started_at'], name='offline_syn_status_039289_idx')],
            },
        ),
        migrations.CreateModel(
            name='MobileSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('background_time', models.IntegerField(default=0)),
                ('foreground_time', models.IntegerField(default=0)),
                ('screens_visited', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('actions_performed', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('api_calls_made', models.IntegerField(default=0)),
                ('network_type', models.CharField(blank=True, max_length=20)),
                ('data_usage_bytes', models.BigIntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mobile_api.mobiledevice')),
            ],
            options={
                'verbose_name': 'Mobile Session',
                'verbose_name_plural': 'Mobile Sessions',
                'db_table': 'mobile_sessions',
                'ordering': ['-session_start'],
                'indexes': [models.Index(fields=['device', 'session_start'], name='mobile_sess_device__4cf081_idx'), models.Index(fields=['is_active'], name='mobile_sess_is_acti_e0d6d7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mobiledevice',
            index=models.Index(fields=['user', 'is_active'], name='mobile_devi_user_id_e78a57_idx'),
        ),
        migrations.AddIndex(
            model_name='mobiledevice',
            index=models.Index(fields=['device_type', 'is_active'], name='mobile_devi_device__7adb8a_idx'),
        ),
        migrations.AddIndex(
            model_name='mobiledevice',
            index=models.Index(fields=['last_seen'], name='mobile_devi_last_se_b78b48_idx'),
        ),
    ]
