# Generated by Django 4.2.7 on 2025-09-10 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('dashboard_type', models.CharField(choices=[('admin', 'مدیریتی'), ('student', 'دانشجویی'), ('faculty', 'هیئت علمی'), ('department', 'دپارتمان'), ('financial', 'مالی'), ('academic', 'آکادمیک'), ('research', 'پژوهشی'), ('library', 'کتابخانه'), ('custom', 'سفارشی')], default='custom', max_length=20, verbose_name='نوع داشبورد')),
                ('is_public', models.BooleanField(default=False, verbose_name='عمومی')),
                ('allowed_roles', models.JSONField(blank=True, default=list, verbose_name='نقش\u200cهای مجاز')),
                ('layout_config', models.JSONField(default=dict, help_text='تنظیمات چیدمان داشبورد', verbose_name='پیکربندی چیدمان')),
                ('refresh_interval', models.PositiveIntegerField(default=300, help_text='بازه به\u200cروزرسانی به ثانیه', verbose_name='بازه به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='آخرین دسترسی')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دسترسی')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='accessible_dashboards', to=settings.AUTH_USER_MODEL, verbose_name='کاربران مجاز')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dashboards', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'داشبورد',
                'verbose_name_plural': 'داشبوردها',
                'db_table': 'analytics_dashboards',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان گزارش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('report_type', models.CharField(help_text='نوع گزارش (student, faculty, financial, etc.)', max_length=50, verbose_name='نوع گزارش')),
                ('data_sources', models.JSONField(default=list, help_text='لیست منابع داده', verbose_name='منابع داده')),
                ('filters', models.JSONField(default=dict, help_text='فیلترهای گزارش', verbose_name='فیلترها')),
                ('grouping', models.JSONField(default=list, help_text='گروه\u200cبندی داده\u200cها', verbose_name='گروه\u200cبندی')),
                ('sorting', models.JSONField(default=list, help_text='مرتب\u200cسازی داده\u200cها', verbose_name='مرتب\u200cسازی')),
                ('frequency', models.CharField(choices=[('real_time', 'بلادرنگ'), ('daily', 'روزانه'), ('weekly', 'هفتگی'), ('monthly', 'ماهانه'), ('quarterly', 'فصلی'), ('yearly', 'سالانه'), ('on_demand', 'درخواستی')], default='on_demand', max_length=20, verbose_name='دوره تکرار')),
                ('schedule_config', models.JSONField(default=dict, help_text='تنظیمات زمان\u200cبندی', verbose_name='پیکربندی زمان\u200cبندی')),
                ('is_public', models.BooleanField(default=False, verbose_name='عمومی')),
                ('allowed_roles', models.JSONField(blank=True, default=list, verbose_name='نقش\u200cهای مجاز')),
                ('export_formats', models.JSONField(default=list, help_text='فرمت\u200cهای خروجی مجاز', verbose_name='فرمت\u200cهای خروجی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('last_generated', models.DateTimeField(blank=True, null=True, verbose_name='آخرین تولید')),
                ('generation_count', models.PositiveIntegerField(default=0, verbose_name='تعداد تولید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='accessible_reports', to=settings.AUTH_USER_MODEL, verbose_name='کاربران مجاز')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش\u200cها',
                'db_table': 'analytics_reports',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=100, verbose_name='نام معیار')),
                ('metric_type', models.CharField(choices=[('student_performance', 'عملکرد دانشجویی'), ('faculty_performance', 'عملکرد هیئت علمی'), ('course_analytics', 'آنالیتیکس درس'), ('financial_metrics', 'معیارهای مالی'), ('system_performance', 'عملکرد سیستم'), ('custom', 'سفارشی')], max_length=50, verbose_name='نوع معیار')),
                ('value', models.JSONField(verbose_name='مقدار')),
                ('context', models.JSONField(default=dict, help_text='زمینه و فیلترهای محاسبه', verbose_name='زمینه')),
                ('period_start', models.DateTimeField(verbose_name='شروع دوره')),
                ('period_end', models.DateTimeField(verbose_name='پایان دوره')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان محاسبه')),
                ('cache_key', models.CharField(help_text='کلید کش برای بازیابی سریع', max_length=255, unique=True, verbose_name='کلید کش')),
                ('expires_at', models.DateTimeField(verbose_name='زمان انقضا')),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='محاسبه\u200cکننده')),
            ],
            options={
                'verbose_name': 'معیار آنالیتیکس',
                'verbose_name_plural': 'معیارهای آنالیتیکس',
                'db_table': 'analytics_metrics',
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('chart_type', models.CharField(choices=[('line', 'خطی'), ('bar', 'ستونی'), ('pie', 'دایره\u200cای'), ('doughnut', 'حلقه\u200cای'), ('area', 'ناحیه\u200cای'), ('scatter', 'پراکندگی'), ('radar', 'رادار'), ('heatmap', 'نقشه حرارتی'), ('gauge', 'عقربه\u200cای'), ('table', 'جدولی'), ('kpi', 'شاخص کلیدی')], default='bar', max_length=20, verbose_name='نوع نمودار')),
                ('data_source', models.CharField(help_text='منبع داده (مدل یا API)', max_length=100, verbose_name='منبع داده')),
                ('query_config', models.JSONField(default=dict, help_text='تنظیمات کوئری داده', verbose_name='پیکربندی کوئری')),
                ('aggregation_config', models.JSONField(default=dict, help_text='تنظیمات تجمیع داده', verbose_name='پیکربندی تجمیع')),
                ('position_x', models.PositiveIntegerField(default=0, verbose_name='موقعیت X')),
                ('position_y', models.PositiveIntegerField(default=0, verbose_name='موقعیت Y')),
                ('width', models.PositiveIntegerField(default=4, verbose_name='عرض')),
                ('height', models.PositiveIntegerField(default=3, verbose_name='ارتفاع')),
                ('chart_config', models.JSONField(default=dict, help_text='تنظیمات نمودار (رنگ، فونت، و...)', verbose_name='پیکربندی نمودار')),
                ('refresh_interval', models.PositiveIntegerField(default=300, verbose_name='بازه به\u200cروزرسانی')),
                ('cache_duration', models.PositiveIntegerField(default=600, verbose_name='مدت کش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='analytics.dashboard', verbose_name='داشبورد')),
            ],
            options={
                'verbose_name': 'ویجت',
                'verbose_name_plural': 'ویجت\u200cها',
                'db_table': 'analytics_widgets',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['dashboard', 'is_active'], name='analytics_w_dashboa_1b6110_idx'), models.Index(fields=['chart_type'], name='analytics_w_chart_t_2a0e02_idx'), models.Index(fields=['order'], name='analytics_w_order_d8d201_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان اجرا')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('running', 'در حال اجرا'), ('completed', 'تکمیل شده'), ('failed', 'شکست خورده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('result_data', models.JSONField(blank=True, help_text='داده\u200cهای نتیجه گزارش', null=True, verbose_name='داده\u200cهای نتیجه')),
                ('row_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد ردیف')),
                ('file_path', models.CharField(blank=True, help_text='مسیر فایل خروجی', max_length=500, verbose_name='مسیر فایل')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='اندازه فایل')),
                ('execution_time', models.FloatField(blank=True, help_text='زمان اجرا به ثانیه', null=True, verbose_name='زمان اجرا')),
                ('memory_usage', models.PositiveIntegerField(blank=True, help_text='استفاده از حافظه به بایت', null=True, verbose_name='استفاده از حافظه')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('error_traceback', models.TextField(blank=True, verbose_name='ردیابی خطا')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_executions', to=settings.AUTH_USER_MODEL, verbose_name='اجراکننده')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='analytics.report', verbose_name='گزارش')),
            ],
            options={
                'verbose_name': 'اجرای گزارش',
                'verbose_name_plural': 'اجراهای گزارش',
                'db_table': 'analytics_report_executions',
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['report', 'status'], name='analytics_r_report__0e9ec7_idx'), models.Index(fields=['executed_by', 'executed_at'], name='analytics_r_execute_5c471a_idx'), models.Index(fields=['status', 'executed_at'], name='analytics_r_status_755fff_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'is_active'], name='analytics_r_report__6ae9a9_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_by', 'frequency'], name='analytics_r_created_5e542c_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='analytics_r_created_59b0e2_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['dashboard_type', 'is_active'], name='analytics_d_dashboa_54c7f9_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['created_by', 'is_public'], name='analytics_d_created_6bbe04_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['created_at'], name='analytics_d_created_0e440c_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsmetric',
            index=models.Index(fields=['metric_type', 'metric_name'], name='analytics_m_metric__e5bb8a_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsmetric',
            index=models.Index(fields=['period_start', 'period_end'], name='analytics_m_period__4821ca_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsmetric',
            index=models.Index(fields=['calculated_at'], name='analytics_m_calcula_bedba2_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsmetric',
            index=models.Index(fields=['expires_at'], name='analytics_m_expires_a9118e_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsmetric',
            index=models.Index(fields=['cache_key'], name='analytics_m_cache_k_41dba1_idx'),
        ),
    ]
