# Generated by Django 4.2.7 on 2025-09-10 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='ایمیل فعال')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='پیامک فعال')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='اعلان پوش فعال')),
                ('in_app_enabled', models.BooleanField(default=True, verbose_name='اعلان درون برنامه فعال')),
                ('websocket_enabled', models.BooleanField(default=True, verbose_name='اعلان بلادرنگ فعال')),
                ('web_enabled', models.BooleanField(default=True, verbose_name='وب فعال')),
                ('flutter_enabled', models.BooleanField(default=True, verbose_name='موبایل فعال')),
                ('telegram_enabled', models.BooleanField(default=False, verbose_name='تلگرام فعال')),
                ('preferences', models.JSONField(default=dict, help_text='تنظیمات تفصیلی برای هر نوع اعلان')),
                ('quiet_hours_enabled', models.BooleanField(default=False, verbose_name='ساعات سکوت فعال')),
                ('quiet_start_time', models.TimeField(blank=True, null=True, verbose_name='شروع ساعات سکوت')),
                ('quiet_end_time', models.TimeField(blank=True, null=True, verbose_name='پایان ساعات سکوت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات اعلان',
                'verbose_name_plural': 'تنظیمات اعلانات',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام قالب')),
                ('type', models.CharField(choices=[('info', 'اطلاعات'), ('success', 'موفقیت'), ('warning', 'هشدار'), ('error', 'خطا'), ('urgent', 'فوری'), ('announcement', 'اعلان'), ('assignment', 'تکلیف'), ('grade', 'نمره'), ('schedule', 'برنامه زمانی'), ('exam', 'امتحان'), ('attendance', 'حضور و غیاب'), ('payment', 'پرداخت'), ('library', 'کتابخانه'), ('message', 'پیام')], max_length=20, verbose_name='نوع اعلان')),
                ('title_template', models.CharField(max_length=200, verbose_name='قالب عنوان')),
                ('message_template', models.TextField(verbose_name='قالب پیام')),
                ('default_channels', models.JSONField(default=list, help_text='کانال\u200cهای پیش\u200cفرض')),
                ('priority', models.CharField(choices=[('low', 'پایین'), ('normal', 'عادی'), ('high', 'بالا'), ('critical', 'بحرانی')], default='normal', max_length=20, verbose_name='اولویت پیش\u200cفرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_real_time', models.BooleanField(default=True, verbose_name='بلادرنگ')),
                ('title_template_en', models.CharField(blank=True, max_length=200, verbose_name='قالب عنوان انگلیسی')),
                ('message_template_en', models.TextField(blank=True, verbose_name='قالب پیام انگلیسی')),
                ('title_template_ar', models.CharField(blank=True, max_length=200, verbose_name='قالب عنوان عربی')),
                ('message_template_ar', models.TextField(blank=True, verbose_name='قالب پیام عربی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'قالب اعلان',
                'verbose_name_plural': 'قالب\u200cهای اعلان',
                'db_table': 'notification_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebSocketConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.CharField(max_length=100, unique=True, verbose_name='شناسه اتصال')),
                ('channel_name', models.CharField(max_length=100, verbose_name='نام کانال')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('user_agent', models.TextField(blank=True, verbose_name='مرورگر کاربر')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('platform', models.CharField(blank=True, max_length=50, verbose_name='پلتفرم')),
                ('connected_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان اتصال')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='آخرین فعالیت')),
                ('disconnected_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان قطع اتصال')),
            ],
            options={
                'verbose_name': 'اتصال وب\u200cسوکت',
                'verbose_name_plural': 'اتصالات وب\u200cسوکت',
                'db_table': 'websocket_connections',
                'ordering': ['-connected_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at', '-priority'], 'verbose_name': 'اعلان', 'verbose_name_plural': 'اعلانات'},
        ),
        migrations.AddField(
            model_name='notification',
            name='action_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='متن دکمه'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, verbose_name='لینک عمل'),
        ),
        migrations.AddField(
            model_name='notification',
            name='channels',
            field=models.JSONField(default=list, help_text='کانال\u200cهای ارسال اعلان'),
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='منقضی می\u200cشود در'),
        ),
        migrations.AddField(
            model_name='notification',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='داده\u200cهای اضافی اعلان'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_real_time',
            field=models.BooleanField(default=True, verbose_name='بلادرنگ'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='ارسال شده'),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'پایین'), ('normal', 'عادی'), ('high', 'بالا'), ('critical', 'بحرانی')], default='normal', max_length=20, verbose_name='اولویت'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان خواندن'),
        ),
        migrations.AddField(
            model_name='notification',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان\u200cبندی شده برای'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'اطلاعات'), ('success', 'موفقیت'), ('warning', 'هشدار'), ('error', 'خطا'), ('urgent', 'فوری'), ('announcement', 'اعلان'), ('assignment', 'تکلیف'), ('grade', 'نمره'), ('schedule', 'برنامه زمانی'), ('exam', 'امتحان'), ('attendance', 'حضور و غیاب'), ('payment', 'پرداخت'), ('library', 'کتابخانه'), ('message', 'پیام')], default='info', max_length=20, verbose_name='نوع اعلان'),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AddField(
            model_name='notification',
            name='websocket_sent',
            field=models.BooleanField(default=False, verbose_name='ارسال وب\u200cسوکت'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='platform',
            field=models.CharField(choices=[('in_app', 'درون برنامه'), ('email', 'ایمیل'), ('sms', 'پیامک'), ('push', 'اعلان پوش'), ('websocket', 'وب\u200cسوکت'), ('web', 'وب'), ('flutter', 'اپلیکیشن موبایل'), ('telegram', 'تلگرام'), ('discord', 'دیسکورد'), ('slack', 'اسلک')], default='web', max_length=20, verbose_name='پلتفرم'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', 'priority'], name='notificatio_type_7e50f5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_for'], name='notificatio_schedul_3d00b6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_real_time', 'websocket_sent'], name='notificatio_is_real_d8e292_idx'),
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
        migrations.AddField(
            model_name='websocketconnection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websocket_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='websocketconnection',
            index=models.Index(fields=['user', 'is_active'], name='websocket_c_user_id_0bac24_idx'),
        ),
        migrations.AddIndex(
            model_name='websocketconnection',
            index=models.Index(fields=['connection_id'], name='websocket_c_connect_f81fa3_idx'),
        ),
    ]
